package sk.upjs.ics.paz1c.obchodnaSiet.forms;

import java.util.List;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.DodavatelDao;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Dodavatel;
import sk.upjs.ics.paz1c.obchodnaSiet.other.DaoFactory;

/**
 *
 * @author Mikey
 */
public class DodavatelForm extends javax.swing.JFrame {

    boolean editMode;
    Dodavatel dodavatel;
    List<Dodavatel> dodavatelia;

    /**
     * Creates new form DodavatelForm
     */
    public DodavatelForm(List<Dodavatel> dodavatelia) {
        init();
        editMode = false;
        this.dodavatel = new Dodavatel();
        this.dodavatelia = dodavatelia;
    }


    public DodavatelForm(List<Dodavatel> dodavatelia, Dodavatel dodavatel) {
        init();
        editMode = true;
        this.dodavatel = dodavatel;
        this.dodavatelia = dodavatelia;
        initTextFields();
    }

    
    private void init() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private void initTextFields() {
        nazovTextField.setText(dodavatel.getNazov());
        sidloTextField.setText(dodavatel.getSidlo());
        kontaktTextField.setText(dodavatel.getKontakt());
        pridatButton.setText("Upraviť");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nazovTextField = new javax.swing.JTextField();
        sidloTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kontaktTextField = new javax.swing.JTextField();
        pridatButton = new javax.swing.JButton();
        spatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pridať dodávateľa");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Názov dodávateľa:");

        nazovTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        sidloTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sidloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidloTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Sídlo:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Kontakt:");

        kontaktTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        pridatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pridatButton.setText("Pridať");
        pridatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatButtonActionPerformed(evt);
            }
        });

        spatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pridatButton)
                .addContainerGap(298, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(spatButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nazovTextField)
                                .addComponent(sidloTextField)
                                .addComponent(kontaktTextField))))
                    .addGap(10, 10, 10)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(pridatButton)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nazovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(sidloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kontaktTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(51, 51, 51)
                    .addComponent(spatButton)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidloTextFieldActionPerformed

    private void pridatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatButtonActionPerformed
        // TODO add your handling code here:

        String nazov = nazovTextField.getText();
        String sidlo = sidloTextField.getText();
        String kontakt = kontaktTextField.getText();

        dodavatel.setNazov(nazov);
        dodavatel.setSidlo(sidlo);
        dodavatel.setKontakt(kontakt);

        DodavatelDao dodavatelDao = DaoFactory.INSTANCE.getDodavatelDao();

        if (editMode) {
            dodavatelDao.saveOrEdit(dodavatel);
        } else {
            dodavatelia.add(dodavatel);
            dodavatelDao.saveOrEdit(dodavatel);
        }

        new ZoznamDodavateliaForm(dodavatelia).setVisible(true);
        dispose();
    }//GEN-LAST:event_pridatButtonActionPerformed

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        new ZoznamDodavateliaForm(dodavatelia).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_spatButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField kontaktTextField;
    private javax.swing.JTextField nazovTextField;
    private javax.swing.JButton pridatButton;
    private javax.swing.JTextField sidloTextField;
    private javax.swing.JButton spatButton;
    // End of variables declaration//GEN-END:variables

}
