/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.obchodnaSiet.forms;

import sk.upjs.ics.paz1c.obchodnaSiet.other.DaoFactory;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.PrijemDao;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.MesacnyNaklad;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.PrijemZProdukty;
import sk.upjs.ics.paz1c.obchodnaSiet.other.enums.FrameMode;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.MesacnyNakladDao;

/**
 *
 * @author Student
 */
public class OdobratNakladPrijemDialogForm extends javax.swing.JDialog {

    /**
     * Creates new form OdobratNakladPrijemDialogForm
     */
    private FrameMode mode;
    private Long id;
    private MesacnyNakladDao daoN;
    private PrijemDao daoP;

    public OdobratNakladPrijemDialogForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public OdobratNakladPrijemDialogForm(java.awt.Frame parent, boolean modal, FrameMode mode, Long id) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.mode = mode;
        this.id = id;
        if (mode == FrameMode.Naklad) {
            daoN = DaoFactory.INSTANCE.getMesacnyNakladDao();
            MesacnyNaklad naklad = daoN.nacitajNaklad(id);
            popisLabel.setText(naklad.getPopis());
            sumaLabel.setText(String.valueOf(naklad.getSuma()));
        }
        if (mode == FrameMode.Prijem) {
            daoP = DaoFactory.INSTANCE.getPrijemDao();
            PrijemZProdukty prijem = daoP.getById(id);
            popisLabel.setText(prijem.getPopis());
            sumaLabel.setText(String.valueOf(prijem.getProduktId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        popisLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sumaLabel = new javax.swing.JLabel();
        odobratButton = new javax.swing.JButton();
        spatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Odobrať");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Popis:");

        popisLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        popisLabel.setText("popis");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Suma:");

        sumaLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sumaLabel.setText("suma");

        odobratButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        odobratButton.setForeground(new java.awt.Color(255, 0, 0));
        odobratButton.setText("Odobrať");
        odobratButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odobratButtonActionPerformed(evt);
            }
        });

        spatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(popisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sumaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(odobratButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(spatButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(popisLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sumaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odobratButton)
                    .addComponent(spatButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_spatButtonActionPerformed

    private void odobratButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odobratButtonActionPerformed
        if (mode == FrameMode.Naklad) {
            daoN.odoberNaklad(id);
        }
        if (mode == FrameMode.Prijem) {
            //daoP.delete(prijemDao.);
        }
        this.dispose();
    }//GEN-LAST:event_odobratButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton odobratButton;
    private javax.swing.JLabel popisLabel;
    private javax.swing.JButton spatButton;
    private javax.swing.JLabel sumaLabel;
    // End of variables declaration//GEN-END:variables
}
