package sk.upjs.ics.paz1c.obchodnaSiet.forms;

import sk.upjs.ics.paz1c.obchodnaSiet.model.ProduktNaPredajniComboBoxModel;
import java.sql.Date;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.DodavatelDao;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.PrevadzkaDao;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.PrijemDao;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.ProduktNaPredajniDao;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Dodavatel;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Prevadzka;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Prijem;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Produkt;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.ProduktNaPredajni;
import sk.upjs.ics.paz1c.obchodnaSiet.model.PrevadzkaComboBoxModel;
import sk.upjs.ics.paz1c.obchodnaSiet.other.DaoFactory;

/**
 *
 * @author Mikey
 */
public class PrijemForm extends javax.swing.JFrame {

    private boolean editMode;
    private Prijem prijem;
    private List<Prijem> prijmy;
    private PrevadzkaDao prevadzkaDao = DaoFactory.INSTANCE.getPrevadzkaDao();
    private ProduktNaPredajniDao produktNaPredajniDao = DaoFactory.INSTANCE.getProduktNaPredajniDao();

    public PrijemForm(List<Prijem> prijmy) {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        editMode = false;
        prijem = new Prijem();
        this.prijmy = prijmy;
    }

    public PrijemForm(List<Prijem> produkty, Prijem prijem) {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        editMode = true;
        this.prijem = prijem;
        this.prijmy = produkty;
        initTextFields();
    }

    private void initTextFields() {
        popisTextField.setText(prijem.getPopis());
        datumTextField.setText(prijem.getDatum().toString());

        if (prijem.getPrevadzkaId() != null) {
            Prevadzka prevadzka = prevadzkaDao.getById(prijem.getPrevadzkaId());
            getPrevadzkyComboBoxModel().setSelectedItem(prevadzka);
        }

        if (prijem.getProduktId() != null) {
            ProduktNaPredajni pnp = produktNaPredajniDao.getById(prijem.getProduktId(), prijem.getPrevadzkaId());

            if (pnp == null) {
                JOptionPane.showMessageDialog(this, "Príjem je sa týka nenaskladneného tovaru, nie je možné ho upravovať");
                spatButtonActionPerformed(null);
            }

            getProduktNaPredajniComboBoxModel().refresh(getSelectedPrevadzka());
            getProduktNaPredajniComboBoxModel().setSelectedItem(pnp);
        }

        kusyTextField.setText(Integer.toString(prijem.getKusy()));

        pridatButton.setText("Upraviť");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        popisTextField = new javax.swing.JTextField();
        datumTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kusyTextField = new javax.swing.JTextField();
        produktNaPredajniLabel = new javax.swing.JLabel();
        pridatButton = new javax.swing.JButton();
        spatButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        prevadzkyComboBox = new javax.swing.JComboBox<>();
        produktNaPredajniComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pridať príjem");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Popis:");

        popisTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        datumTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        datumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Dátum:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Kusy:");

        kusyTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        produktNaPredajniLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        produktNaPredajniLabel.setText("Produkt:");

        pridatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pridatButton.setText("Pridať");
        pridatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatButtonActionPerformed(evt);
            }
        });

        spatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Prevádzka:");

        prevadzkyComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        prevadzkyComboBox.setModel(new sk.upjs.ics.paz1c.obchodnaSiet.model.PrevadzkaComboBoxModel());
        prevadzkyComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                prevadzkyComboBoxMousePressed(evt);
            }
        });
        prevadzkyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevadzkyComboBoxActionPerformed(evt);
            }
        });
        prevadzkyComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                prevadzkyComboBoxPropertyChange(evt);
            }
        });

        produktNaPredajniComboBox.setModel(new ProduktNaPredajniComboBoxModel(getSelectedPrevadzka()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pridatButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spatButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(produktNaPredajniLabel)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datumTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(popisTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kusyTextField)
                            .addComponent(prevadzkyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(produktNaPredajniComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(popisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(datumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(prevadzkyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produktNaPredajniLabel)
                    .addComponent(produktNaPredajniComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kusyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridatButton)
                    .addComponent(spatButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datumTextFieldActionPerformed

    private void pridatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatButtonActionPerformed
        // TODO add your handling code here:

        ProduktNaPredajni pnp = getSelectedProduktNaPredajni();
        try {
            int kusy = Integer.parseInt(kusyTextField.getText());
            if (pnp == null || kusy > pnp.getKusy()) {
                JOptionPane.showMessageDialog(this, "Upravte výber");
                return;
            }
            prijem.setKusy(kusy);
            String popis = popisTextField.getText();

            prijem.setPopis(popis);
            prijem.setDatum(Date.valueOf(datumTextField.getText()));

            prijem.setPrevadzkaId(pnp.getPrevadzkaId());
            prijem.setProduktId(pnp.getProduktId());
            prijem.setZlava(pnp.getZlava());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Upravte výber");
            return;
        }
        PrijemDao produktDao = DaoFactory.INSTANCE.getPrijemDao();

        if (editMode) {
            produktDao.edit(prijem);
        } else {
            prijmy.add(prijem);
            produktDao.save(prijem);
        }

        new ZoznamPrijemForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pridatButtonActionPerformed

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        new ZoznamPrijemForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_spatButtonActionPerformed

    private void prevadzkyComboBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevadzkyComboBoxMousePressed

    }//GEN-LAST:event_prevadzkyComboBoxMousePressed

    private void prevadzkyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevadzkyComboBoxActionPerformed
        Prevadzka selectedPrevadzka = (Prevadzka) prevadzkyComboBox.getSelectedItem();
        if (selectedPrevadzka == null) {
            return;
            // zamestnanci = zamestnanecDao.getZamestnanci();
        } else {
            getProduktNaPredajniComboBoxModel().refresh(selectedPrevadzka);
        }

    }//GEN-LAST:event_prevadzkyComboBoxActionPerformed

    private void prevadzkyComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_prevadzkyComboBoxPropertyChange

    }//GEN-LAST:event_prevadzkyComboBoxPropertyChange

    private PrevadzkaComboBoxModel getPrevadzkyComboBoxModel() {
        return (PrevadzkaComboBoxModel) prevadzkyComboBox.getModel();
    }

    private Prevadzka getSelectedPrevadzka() {
        return (Prevadzka) getPrevadzkyComboBoxModel().getSelectedItem();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datumTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField kusyTextField;
    private javax.swing.JTextField popisTextField;
    private javax.swing.JComboBox<Prevadzka> prevadzkyComboBox;
    private javax.swing.JButton pridatButton;
    private javax.swing.JComboBox<ProduktNaPredajni> produktNaPredajniComboBox;
    private javax.swing.JLabel produktNaPredajniLabel;
    private javax.swing.JButton spatButton;
    // End of variables declaration//GEN-END:variables

    private ProduktNaPredajniComboBoxModel getProduktNaPredajniComboBoxModel() {
        return (ProduktNaPredajniComboBoxModel) produktNaPredajniComboBox.getModel();
    }

    private ProduktNaPredajni getSelectedProduktNaPredajni() {
        return (ProduktNaPredajni) getProduktNaPredajniComboBoxModel().getSelectedItem();
    }
}
