/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.obchodnaSiet.forms;

import sk.upjs.ics.paz1c.obchodnaSiet.other.DaoFactory;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.PrevadzkaDao;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Naklad;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Prevadzka;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Prijem;
import sk.upjs.ics.paz1c.obchodnaSiet.model.NakladListModel;
import sk.upjs.ics.paz1c.obchodnaSiet.model.PrijemListModel;
import sk.upjs.ics.paz1c.obchodnaSiet.other.enums.FrameMode;

/**
 *
 * @author Student
 */
public class ProduktNakladPrevadzkyForm extends javax.swing.JFrame {

    /**
     * Creates new form ProduktNakladPrevadzkyForm
     */
    
    PrevadzkaDao dao = DaoFactory.INSTANCE.getPrevadzkaDao();
    Prevadzka prevadzka;
    
    public ProduktNakladPrevadzkyForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public ProduktNakladPrevadzkyForm(Long id) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        prevadzka = dao.getById(id);
        nazovPrevadzkyLabel.setText(prevadzka.getNazov());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nazovPrevadzkyLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nakladyList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        prijmyList = new javax.swing.JList<>();
        pridatNakladButton = new javax.swing.JButton();
        odobratNakladButton = new javax.swing.JButton();
        pridatPrijemButton = new javax.swing.JButton();
        odobratPrijemButton = new javax.swing.JButton();
        spatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        nazovPrevadzkyLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nazovPrevadzkyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nazovPrevadzkyLabel.setText("Názov prevádzky");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Náklady:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Príjmy:");

        nakladyList.setModel(new sk.upjs.ics.paz1c.obchodnaSiet.model.NakladListModel());
        jScrollPane1.setViewportView(nakladyList);

        prijmyList.setModel(new sk.upjs.ics.paz1c.obchodnaSiet.model.PrijemListModel());
        jScrollPane2.setViewportView(prijmyList);

        pridatNakladButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pridatNakladButton.setText("Pridať");
        pridatNakladButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatNakladButtonActionPerformed(evt);
            }
        });

        odobratNakladButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        odobratNakladButton.setText("Odobrať");
        odobratNakladButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odobratNakladButtonActionPerformed(evt);
            }
        });

        pridatPrijemButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pridatPrijemButton.setText("Pridať");
        pridatPrijemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatPrijemButtonActionPerformed(evt);
            }
        });

        odobratPrijemButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        odobratPrijemButton.setText("Odobrať");
        odobratPrijemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odobratPrijemButtonActionPerformed(evt);
            }
        });

        spatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nazovPrevadzkyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pridatNakladButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(odobratNakladButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pridatPrijemButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(odobratPrijemButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(spatButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nazovPrevadzkyLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridatNakladButton)
                    .addComponent(odobratNakladButton)
                    .addComponent(pridatPrijemButton)
                    .addComponent(odobratPrijemButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spatButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        new ZoznamPrevadzkyForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_spatButtonActionPerformed

    private void pridatNakladButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatNakladButtonActionPerformed
        new PridatNakladPrijemDialogForm(this, true, FrameMode.Naklad, prevadzka.getId()).setVisible(true);
        NakladListModel model = (NakladListModel) nakladyList.getModel();
        model.refresh();
    }//GEN-LAST:event_pridatNakladButtonActionPerformed

    private void pridatPrijemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatPrijemButtonActionPerformed
        new PridatNakladPrijemDialogForm(this, true, FrameMode.Prijem, prevadzka.getId()).setVisible(true);
        PrijemListModel model = (PrijemListModel) prijmyList.getModel();
        model.refresh();
    }//GEN-LAST:event_pridatPrijemButtonActionPerformed

    private void odobratNakladButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odobratNakladButtonActionPerformed
        Naklad naklad = new Naklad();
        naklad = nakladyList.getSelectedValue();
        new OdobratNakladPrijemDialogForm(this, true, FrameMode.Naklad, naklad.getId()).setVisible(true);
        NakladListModel model = (NakladListModel) nakladyList.getModel();
        model.refresh();
    }//GEN-LAST:event_odobratNakladButtonActionPerformed

    private void odobratPrijemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odobratPrijemButtonActionPerformed
        Prijem prijem = new Prijem();
        prijem = prijmyList.getSelectedValue();
        new OdobratNakladPrijemDialogForm(this, true, FrameMode.Prijem, prijem.getId()).setVisible(true);
        PrijemListModel model = (PrijemListModel) prijmyList.getModel();
        model.refresh();
    }//GEN-LAST:event_odobratPrijemButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Naklad> nakladyList;
    private javax.swing.JLabel nazovPrevadzkyLabel;
    private javax.swing.JButton odobratNakladButton;
    private javax.swing.JButton odobratPrijemButton;
    private javax.swing.JButton pridatNakladButton;
    private javax.swing.JButton pridatPrijemButton;
    private javax.swing.JList<Prijem> prijmyList;
    private javax.swing.JButton spatButton;
    // End of variables declaration//GEN-END:variables
}
