/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.obchodnaSiet.forms;

import java.util.List;
import javax.swing.JOptionPane;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.PrevadzkaDao;
import sk.upjs.ics.paz1c.obchodnaSiet.other.DaoFactory;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Prevadzka;
import sk.upjs.ics.paz1c.obchodnaSiet.model.PrevadzkyTableModel;

/**
 *
 * @author Student
 */
public class ZoznamPrevadzkyForm extends javax.swing.JFrame {

    private static final String OZNACTE_PREVADZKU_MESSAGE = "Označte prevádzku";

    private List<Prevadzka> prevadzky;
    private PrevadzkaDao prevadzkaDao = DaoFactory.INSTANCE.getPrevadzkaDao();

    /**
     * Creates new form PrevadzkyForm
     */
    public ZoznamPrevadzkyForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        prevadzky = prevadzkaDao.getPrevadzky();
        refreshPrevadzkyTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        detailPrevadzkyButton = new javax.swing.JButton();
        pridatPrevadzkuButton = new javax.swing.JButton();
        odobratPrevadzkuButton = new javax.swing.JButton();
        spatButton = new javax.swing.JButton();
        upravitPrevadzkuButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        prevadzkyTable = new javax.swing.JTable();
        nakladButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prevádzky");

        detailPrevadzkyButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        detailPrevadzkyButton.setText("Príjmy");
        detailPrevadzkyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailPrevadzkyButtonActionPerformed(evt);
            }
        });

        pridatPrevadzkuButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pridatPrevadzkuButton.setText("Pridať prevádzku");
        pridatPrevadzkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatPrevadzkuButtonActionPerformed(evt);
            }
        });

        odobratPrevadzkuButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        odobratPrevadzkuButton.setText("Odobrať prevádzku");
        odobratPrevadzkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odobratPrevadzkuButtonActionPerformed(evt);
            }
        });

        spatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        upravitPrevadzkuButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        upravitPrevadzkuButton.setText("Upraviť prevádzku");
        upravitPrevadzkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravitPrevadzkuButtonActionPerformed(evt);
            }
        });

        prevadzkyTable.setModel(new PrevadzkyTableModel(prevadzky));
        jScrollPane2.setViewportView(prevadzkyTable);

        nakladButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nakladButton.setText("Náklady");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pridatPrevadzkuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(detailPrevadzkyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nakladButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upravitPrevadzkuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(odobratPrevadzkuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spatButton)
                        .addGap(1, 1, 1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(pridatPrevadzkuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailPrevadzkyButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(upravitPrevadzkuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odobratPrevadzkuButton)
                            .addComponent(nakladButton)
                            .addComponent(spatButton))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        new HlavneOknoForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_spatButtonActionPerformed

    private void detailPrevadzkyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailPrevadzkyButtonActionPerformed
        Prevadzka prevadzka = getSelectedPrevadzka();
//        if (prevadzka == null) {
//            JOptionPane.showMessageDialog(this, OZNACTE_PREVADZKU_MESSAGE);
//            return;
//        }
        // new ProduktNakladPrevadzkyForm(prevadzka.getId()).setVisible(true);
        new ZoznamPrijemForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_detailPrevadzkyButtonActionPerformed

    private void odobratPrevadzkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odobratPrevadzkuButtonActionPerformed
        Prevadzka prevadzka = getSelectedPrevadzka();
        if (prevadzka == null) {
            JOptionPane.showMessageDialog(this, OZNACTE_PREVADZKU_MESSAGE);
            return;
        }
        prevadzky.remove(prevadzka);
        new OdobratPrevadzkuDialogForm(this, true, prevadzka.getId()).setVisible(true);
        refreshPrevadzkyTableModel();
    }//GEN-LAST:event_odobratPrevadzkuButtonActionPerformed

    private void pridatPrevadzkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatPrevadzkuButtonActionPerformed
        new PrevadzkaForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_pridatPrevadzkuButtonActionPerformed

    private void upravitPrevadzkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravitPrevadzkuButtonActionPerformed
        Prevadzka prevadzka = getSelectedPrevadzka();
        if (prevadzka == null) {
            JOptionPane.showMessageDialog(this, OZNACTE_PREVADZKU_MESSAGE);
            return;
        }
        new PrevadzkaForm(prevadzka).setVisible(true);
        refreshPrevadzkyTableModel();
        dispose();
    }//GEN-LAST:event_upravitPrevadzkuButtonActionPerformed

    private Prevadzka getSelectedPrevadzka() {
        int selectedRow = prevadzkyTable.getSelectedRow();
        if (selectedRow == -1) {
            return null;
        } else {
            return getPrevadzkyTableModel().getItemAt(selectedRow);
        }
    }

    private void refreshPrevadzkyTableModel() {
        PrevadzkyTableModel model = getPrevadzkyTableModel();
        model.refresh(prevadzky);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailPrevadzkyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nakladButton;
    private javax.swing.JButton odobratPrevadzkuButton;
    private javax.swing.JTable prevadzkyTable;
    private javax.swing.JButton pridatPrevadzkuButton;
    private javax.swing.JButton spatButton;
    private javax.swing.JButton upravitPrevadzkuButton;
    // End of variables declaration//GEN-END:variables

    private PrevadzkyTableModel getPrevadzkyTableModel() {
        return (PrevadzkyTableModel) prevadzkyTable.getModel();
    }
}
