package sk.upjs.ics.paz1c.obchodnaSiet.forms;

import java.util.List;
import javax.swing.JOptionPane;
import sk.upjs.ics.paz1c.obchodnaSiet.dao.interfaces.DodavatelDao;
import sk.upjs.ics.paz1c.obchodnaSiet.entity.Dodavatel;
import sk.upjs.ics.paz1c.obchodnaSiet.model.DodavatelTableModel;
import sk.upjs.ics.paz1c.obchodnaSiet.other.DaoFactory;

/**
 *
 * @author Mikey
 */
public class ZoznamDodavateliaForm extends javax.swing.JFrame {

    private static final String OZNACTE_PRODUKT_MESSAGE = "Označte dodávateľa";

    private List<Dodavatel> dodavatelia;
    private DodavatelDao dodavatelDao = DaoFactory.INSTANCE.getDodavatelDao();

    /**
     * Creates new form ZoznamDodavateliaForm
     */
    public ZoznamDodavateliaForm(List<Dodavatel> dodavatelia) {
        setUndecorated(true);
        initComponents();
        this.dodavatelia = dodavatelia;
        this.setLocationRelativeTo(null);
        refreshDodavatelTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pridatProduktButton = new javax.swing.JButton();
        odobratDodavatelaButton = new javax.swing.JButton();
        upravitDodavatelaButton = new javax.swing.JButton();
        spatButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dodavatelTable = new javax.swing.JTable();
        dodavateliaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pridatProduktButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pridatProduktButton.setText("Pridať dodávateľa");
        pridatProduktButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatProduktButtonActionPerformed(evt);
            }
        });

        odobratDodavatelaButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        odobratDodavatelaButton.setText("Odobrať dodávateľa");
        odobratDodavatelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odobratDodavatelaButtonActionPerformed(evt);
            }
        });

        upravitDodavatelaButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        upravitDodavatelaButton.setText("Upraviť dodávateľa");
        upravitDodavatelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravitDodavatelaButtonActionPerformed(evt);
            }
        });

        spatButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        spatButton.setText("Späť");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        dodavatelTable.setModel(new DodavatelTableModel(dodavatelia));
        jScrollPane2.setViewportView(dodavatelTable);

        dodavateliaLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dodavateliaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dodavateliaLabel.setText("Dodávatelia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(dodavateliaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pridatProduktButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(odobratDodavatelaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upravitDodavatelaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dodavateliaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridatProduktButton)
                    .addComponent(upravitDodavatelaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spatButton)
                    .addComponent(odobratDodavatelaButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridatProduktButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatProduktButtonActionPerformed
        new DodavatelForm(dodavatelia).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pridatProduktButtonActionPerformed

    private void odobratDodavatelaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odobratDodavatelaButtonActionPerformed
        Dodavatel dodavatel = getSelectedDodavatel();
        if (dodavatel == null) {
            JOptionPane.showMessageDialog(this, OZNACTE_PRODUKT_MESSAGE);
            return;
        }
        //new OdobratProduktDialogForm(this, true, produkt).setVisible(true);
        dodavatelDao.delete(dodavatel);
        dodavatelia = dodavatelDao.getDodavatelia();

        refreshDodavatelTableModel();
    }//GEN-LAST:event_odobratDodavatelaButtonActionPerformed

    private void upravitDodavatelaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravitDodavatelaButtonActionPerformed
        Dodavatel dodavatel = getSelectedDodavatel();
        if (dodavatel == null) {
            JOptionPane.showMessageDialog(this, OZNACTE_PRODUKT_MESSAGE);
            return;
        }
        new DodavatelForm(dodavatelia, dodavatel).setVisible(true);
        dispose();
    }//GEN-LAST:event_upravitDodavatelaButtonActionPerformed

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
        new HlavneOknoForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_spatButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dodavatelTable;
    private javax.swing.JLabel dodavateliaLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton odobratDodavatelaButton;
    private javax.swing.JButton pridatProduktButton;
    private javax.swing.JButton spatButton;
    private javax.swing.JButton upravitDodavatelaButton;
    // End of variables declaration//GEN-END:variables

    private Dodavatel getSelectedDodavatel() {
        int selectedRow = dodavatelTable.getSelectedRow();
        if (selectedRow == -1) {
            return null;
        } else {
            return getProduktTableModel().getItemAt(selectedRow);
        }
    }

    private void refreshDodavatelTableModel() {
        DodavatelTableModel model = getProduktTableModel();
        model.refresh(dodavatelia);
    }

    private DodavatelTableModel getProduktTableModel() {
        return (DodavatelTableModel) dodavatelTable.getModel();
    }
}
